### ISSUE TITLE
Clarification for question "Which admission controller runs first in Kubernetes?"

### ISSUE THREAD

**Issue by amimas** [thiago4go/kubernetes-security-kcsa-mock#10]
HI @thiago4go,

Would you be able to help clarifying the question "Which admission controller runs first in Kubernetes?".

https://github.com/thiago4go/kubernetes-security-kcsa-mock/blob/906b63e68e503ffe4bf1c547ed882f2eeb23094b/src/questions.js#L72-L85

I can't seem to find a reference in Kubernetes documentation that mentions the order specifically. What the docs does say about ordering is following about [admission control phases](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#admission-control-phases):

> The admission control process proceeds in two phases. In the first phase, mutating admission controllers are run. In the second phase, validating admission controllers are run. Note again that some of the controllers are both.

The above is referring to ordering between the types of admission controllers. The options listed for the answer are simply name of individual admission controller plugins. Since I couldn't find the order in kubernetes docs, I tried to search but didn't find any concrete reference from google search. Tried chatgpt and that seems to indicate the `NamespaceLifecycle` admission controller will run first. Not sure where chatgpt is getting that info.

<img width="727" alt="image" src="https://github.com/user-attachments/assets/32ba2831-0ca4-4bdd-96c3-e16c5f3e0802" />

Do you happen to know where I can find a reference to order between the full list of admission controllers?

**Comment by thiago4go** [comment]
Hi @amimas. You correctly point to the documentation that explains this topic.
Since **mutating** types run before **validating** ones, the only possible correct answer is `MutatingAdmissionWebhook`

ValidatingAdmissionWebhook
Type: Validating.

MutatingAdmissionWebhook 
Type: Mutating.

ResourceQuota
Type: Validating.

NamespaceLifecycle 
Type: Validating.

NamespaceLifecycle
Type: Validating.

AlwaysPullImages
Type: Mutating and Validating.
